name: Build (Manual)

permissions:
  contents: read

on:
  push:
    branches-ignore: [dev]
    paths-ignore:
      - '**/.editorconfig'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '**/*.md'
      - '**/LICENSE'
      - '**/LICENCE'
      - 'PCL.Core.Test/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
  workflow_dispatch:
    inputs:
      architecture:
        description: 目标架构
        type: choice
        options: [x64, ARM64, all]
        default: x64
      configuration:
        description: 构建配置
        type: choice
        options: [CI, Beta, Release]
        default: CI

jobs:
  build:
    strategy:
      matrix:
        architecture: ${{ (github.event_name == 'push' || inputs.architecture == 'all') && fromJSON('["x64", "ARM64"]') || fromJSON(format('["{0}"]', inputs.architecture)) }}
      fail-fast: false

    uses: ./.github/workflows/reusable-build.yml
    with:
      configuration: ${{ github.event_name == 'push' && 'CI' || inputs.configuration }}
      architecture: ${{ matrix.architecture }}
    secrets: inherit
